# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 09:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gateway_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='ip_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='route_map',
            name='prefix',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
