# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 13:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0003_auto_20180622_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='ip_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(protocol='IPv4'), size=None),
        ),
    ]
